version: '2.1'
services:
  cq-mysql:
    container_name: coursequest-mysql
    image: 'mysql:latest'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: CourseQuest
      MYSQL_ROOT_PASSWORD: Fyc8623579779
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    restart: always
  cq-app:
    image: coursequest-spring-boot-app
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - /data/coursequest-spring-boot-app
    depends_on:
      - cq-mysql