version: '2.1'
services:
  cq-mysql:
    container_name: coursequest-mysql
    image: 'mysql:latest'
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: coursequest
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3301:3306'
    restart: always
  cq-app:
    image: coursequest-spring-boot-app
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - /data/coursequest-spring-boot-app
    depends_on:
      - cq-mysql