spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  profiles:
    include: default
  security:
    user:
      name: test
      password: 123456
      roles:
        - user
        - admin
server:
  port: 8080

