spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CourseQuest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  profiles:
    include: default
  security:
    user:
      name: test
      password: 123456
      roles:
        - user
        - admin
    oauth2:
      client:
        registration:
          google:
            client-id: 590629088207-ta5nudl72tbcseavnji0dspl4dg24323.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

server:
  port: 8080
  servlet:
    context-path: /

application:
  metadata-file-path: src/main/resources/static/data.csv
  webscraping:
    urls: [https://cs.vt.edu/Undergraduate/courses.html]
  labels:
    degreetypes: 
      phd: Phd
      pg: Masters
      ug: UG